export const REPROCESSING ={
    MOLIENDA: "MOLIENDA",
    DESCONGELAMIENTO: "DESCONGELAMIENTO",
    EMBUTIDO: "EMBUTIDO",
    ACONDICIONAMIENTO: "ACONDICIONAMIENTO",
    INJECCIONTENDERIZADO: "INJECCIONTENDERIZADO"
}